### ISSUE TITLE
gstreamer 内存泄漏

### ISSUE THREAD

**Issue by lytasky** [gesanqiu/gstreamer-example#1]
rtspsrc location=rtsp://admin:admin123@172.23.240.20:554/cam/realmonitor?channel=1&subtype=0 latency=0 drop-on-latency=true ! rtph264depay ! h264parse ! omxh264dec ! nvvidconv ! video/x-raw, format=(string)NV12  ! appsink emit-signals=true sync=false max-buffers=1 drop=true

你好，我使用的是jetson nano,然后通过上面的gst-url 使用new-sample、pull-sample 来获取摄像头的每一帧 ，随着运行过程中 内存会一直增加，请问有什么解决思路吗？

**Comment by gesanqiu** [comment]
手头没有测试环境，暂时我能想到的有两点。
1.appsink出来的sample，你在用完之后需要手动调用`gst_sample_unref(sample);`释放掉，不知道你sink出来的sample是否得到了正确的释放。我的测试程序里通过cv::Mat和std::shared_ptr做了sample下的内存管理，相当于使用std::shared_ptr<cv::Mat>接管了sample下的buffer内存，这种做法其实是不严谨的，我感觉还是会产生一些细微的内存碎片。正确的做法应该是定义一个class然后封装一个GstSample*对象，然后用这个class的对象接管sink出来的GstSample*，并在对象析构的时候调用`gst_sample_unref(sample);`。
2.假如不是由于appsink插件导致的内存泄露，那么我建议你逐个插件调研，看看是不是`omxh264dec`这个解码器导致的内存泄露，比如说你把appsink改成fakesink，然后用`free`看memory的使用和释放情况。高通的硬件解码器在早期是会导致内存泄露的，当时解了挺长时间，不过我觉得`omxh264dec`应该是一个很成熟的插件了，不会存在这种问题。
最后就是Jetson我建议用DeepStream开发，Nvidia论坛上的CE回复问题还挺快的。

**Comment by lytasky** [comment]
嗯 收到 我这边排查下来还有一个怀疑思路：有可能是omxh264dec、nvvidconv 并发太多导致硬件资源不够，导致内存会有buffer或者别的缓存等导致的？ 但是不确定怎么去确定(我们是python3的程序)。因为我们发现把并发讲下来（比如从8到1），基本就没有增长了。

**Comment by gesanqiu** [comment]
python是否有valgrind这样的内存泄漏的追查工具呢，我不太了解Python，这类边缘盒子设备还是尽量用C++开发吧orz。
1.假如你怀疑硬件资源不够，你那边是否有jetson nx这种比nano性能更强的设备，跑起来看看呢？
2.假如是omxh264enc的问题，解决起来难度会很大，我这边能给的思路就是去看看omxh264dec的各个锁的持有情况，是不是buffer被锁住了一直没释放（qtivdec上是这个原因导致的，但是细节因为是机密所以不能透露更多）。
3.降并发的情况下，你延长测试时间是否还有泄露，可以写个脚本每隔一段时间看一下内存的状态，跑满几个小时 看看。另外假如降并发有效，那么你可以保持原有并发数，但是降低rtsp camera的帧数和分辨率，看看内存消耗的情况。

**Comment by lytasky** [comment]
好的 非常感谢   按着你上面的思路我去试试
